"""Story 6.3 — Smoke test for `bot.py` pipeline wiring (AC3, AC9).

`run_bot` cannot be invoked synchronously in tests (it blocks on a real
LiveKit connection), so this test introspects the bot module's source and
asserts the emitter is imported AND instantiated in the right relative
position. The test is a wiring guard — a future refactor that moves the
emitter out of order (or removes it) would fail this test loudly.

Story 6.3b removed `VisemeEmitter` from the pipeline entirely: visemes
are now generated client-side from the PCM audio buffer about to hit the
speaker, so no server-side emitter exists. Story 6.29 then retired
`EmotionEmitter` too — the face emotion is co-generated by the reply LLM
as a trailing mood tag, stripped + re-emitted by `ReplySanitizer` (which
the wiring assertions below now pin between the LLM and the TTS).
"""

from __future__ import annotations

import pathlib

_BOT_PATH = pathlib.Path(__file__).resolve().parent.parent / "pipeline" / "bot.py"


def test_bot_imports_emitter_classes() -> None:
    """`bot.py` imports `ReplySanitizer` (Story 6.29) + `PatienceTracker` +
    `CheckpointManager` + `ExchangeClassifier` (Story 6.6) +
    `COHERENCE_CHARTER` + `MOOD_TAG_DIRECTIVE` + `DTLNAudioFilter`
    (Story 6.9), and does NOT import the removed `VisemeEmitter` nor the
    Story 6.29-retired `EmotionEmitter`."""
    source = _BOT_PATH.read_text(encoding="utf-8")
    # Story 6.29 — EmotionEmitter retired (mood co-generated by the reply
    # LLM, stripped/re-emitted by ReplySanitizer). Comments may still
    # reference the old name for history; CODE must not.
    assert "from pipeline.reply_sanitizer import ReplySanitizer" in source
    code_lines = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert "EmotionEmitter" not in code_lines
    assert "from pipeline.patience_tracker import PatienceTracker" in source
    # Story 6.10 — `bot.py` now imports CheckpointManager + the two
    # goal-composition helpers from a multi-line import block, so assert
    # the module + symbol rather than a single-line import string.
    assert "from pipeline.checkpoint_manager import (" in source
    assert "CheckpointManager," in source
    assert "format_remaining_goals_block," in source
    assert "format_suggested_focus_block," in source
    assert "from pipeline.exchange_classifier import ExchangeClassifier" in source
    # 2026-05-29 all-Groq migration + provider abstraction — the main
    # character LLM is built by the single switch-point factory
    # `pipeline/llm_provider.build_main_llm` (OpenAILLMService pointed at
    # the configured base_url lives THERE, not inline in bot.py). Was
    # OpenRouterLLMService/Qwen, which 429'd on OpenRouter's shared pool.
    assert "from pipeline.llm_provider import (" in source
    assert "build_main_llm," in source
    assert "resolve_llm_api_key," in source
    # raw-httpx sites need the FULL chat-completions URL (resolve_llm_chat_url),
    # not the base — conflating them was the checkpoints-404 regression.
    assert "resolve_llm_chat_url," in source
    assert "OpenRouterLLMService" not in source
    # Story 6.8 Phase 2 AC8 — wiring assertion for the charter import.
    assert "COHERENCE_CHARTER" in source
    # Story 6.9 — DTLN noise suppression must be imported AND wired into
    # LiveKitParams(audio_in_filter=...).
    assert "from pipeline.dtln_audio_filter import DTLNAudioFilter" in source
    # Story 6.9 review patch (D3) — EndpointWatchdog backstop for Soniox
    # endpoint detection. Imported AND positioned immediately after STT
    # in the pipeline (see `test_bot_pipeline_ordering` below).
    assert "from pipeline.endpoint_watchdog import EndpointWatchdog" in source
    # Story 6.11 — EnvironmentMonitor (parasitic-voice detection).
    assert "from pipeline.environment_monitor import EnvironmentMonitor" in source
    # Story 6.11 fix — InputGate ("stop listening" so the noise exit line
    # can't be interrupted).
    assert "from pipeline.input_gate import InputGate" in source
    assert "VisemeEmitter" not in source


def test_bot_wires_input_gate_first_and_arms_via_monitor() -> None:
    """Story 6.11 fix (call_id=205) — InputGate must sit at the TOP of the
    pipeline (after transport.input(), before stt) so muting starves the
    VAD + STT at the source, and EnvironmentMonitor must receive it so it can
    arm it on detection."""
    source = _BOT_PATH.read_text(encoding="utf-8")
    assert "InputGate()" in source
    assert "input_gate=input_gate" in source  # threaded into EnvironmentMonitor

    start = source.find("pipeline = Pipeline(")
    end = source.find("task = PipelineTask", start)
    block = "\n".join(
        line
        for line in source[start:end].splitlines()
        if not line.lstrip().startswith("#")
    )

    def _idx(needle: str) -> int:
        i = block.find(needle)
        assert i != -1, f"missing pipeline element: {needle!r}"
        return i

    assert _idx("transport.input()") < _idx("input_gate") < _idx("stt")


def test_bot_enables_soniox_speaker_diarization() -> None:
    """Story 6.11 AC1 — `enable_speaker_diarization=True` on the Soniox
    settings. Without it, `TranscriptionFrame.result` carries no `speaker`
    ids and EnvironmentMonitor can never detect a parasitic voice."""
    source = _BOT_PATH.read_text(encoding="utf-8")
    body = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert "enable_speaker_diarization=True" in body


def test_bot_instantiates_and_wires_environment_monitor() -> None:
    """Story 6.11 AC2 — EnvironmentMonitor is constructed with the call's
    PatienceTracker, and the noisy-environment exit line is threaded into
    PatienceTracker from the resolved config."""
    source = _BOT_PATH.read_text(encoding="utf-8")
    # Construction is multi-line since the Story 6.11 InputGate fix
    # (patience_tracker= + input_gate= kwargs) — assert symbol + kwarg, not a
    # single-line call string.
    assert "EnvironmentMonitor(" in source
    assert "patience_tracker=patience_tracker" in source
    assert "hang_up_line_noisy_environment=patience_config[" in source
    assert '"hang_up_line_noisy_environment"' in source


def test_bot_wires_dtln_audio_filter_into_livekit_params() -> None:
    """Story 6.9 — the DTLN noise suppression filter MUST be passed to
    `LiveKitParams(audio_in_filter=...)`. Pipecat applies `audio_in_filter`
    BEFORE VAD + STT, so the entire downstream chain (Silero VAD, Soniox,
    emotion + exchange classifiers, CheckpointManager, PatienceTracker)
    sees denoised audio. A missing wiring would silently leave the call
    on noisy audio — the smoke gate would catch it, but the wiring test
    catches the regression at pre-commit time.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert "DTLNAudioFilter(" in code, (
        "bot.py must instantiate DTLNAudioFilter — found import but no "
        "construction site"
    )
    assert "audio_in_filter=audio_in_filter" in code, (
        "bot.py must pass the DTLNAudioFilter instance to "
        "LiveKitParams(audio_in_filter=...) — otherwise the filter is "
        "constructed but never wired into the audio path"
    )


def test_bot_dtln_has_env_kill_switch() -> None:
    """Story 6.13 follow-up — DTLN must be gated by `DTLN_ENABLED` (default
    on) so it can be disabled via env + restart for the connection-jitter
    A/B (does DTLN's per-frame ONNX inference on the 2-core VPS starve the
    asyncio loop → bursty audio-out → 5G playout stretch?) and for ops,
    without a code release. When disabled, `audio_in_filter` falls back to
    None — pipecat's no-filter default.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert 'os.environ.get("DTLN_ENABLED"' in code, (
        "bot.py must gate DTLN behind the DTLN_ENABLED env var so it can be "
        "toggled via env + restart"
    )
    assert "audio_in_filter = None" in code, (
        "the DTLN-disabled branch must set audio_in_filter=None "
        "(pipecat no-filter default)"
    )


def test_bot_instantiates_emitters() -> None:
    """`bot.py` instantiates `ReplySanitizer` (Story 6.29) + `PatienceTracker`
    with the expected constructor args. `VisemeEmitter` must NOT appear
    anywhere; the retired `EmotionEmitter` construction (and its
    `settings.emotion_model` read — the field is legacy now) must be gone.

    PatienceTracker is constructed via explicit keyword extraction from
    `patience_config` (Story 6.4 cleanup) so future changes to the
    `_DIFFICULTY_PRESETS` shape don't silently break this constructor.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    # Story 6.29 — the sanitizer replaces the EmotionEmitter construction.
    # Story 10.6 review (D4) — now constructed with the per-scenario never-silent
    # floor line (in-character, vs the global "Go on.").
    assert "ReplySanitizer(" in source
    assert "fallback_line=load_scenario_never_silent_fallback(scenario_id)" in source
    assert "EmotionEmitter(" not in source
    assert "model=settings.emotion_model" not in source
    assert "PatienceTracker(" in source
    # All 8 fields returned by `resolve_patience_config` are passed to
    # the PatienceTracker constructor (Deviation #15). The 4 dormant
    # fields are stored on the instance for forward-compat with Stories
    # 6.6 / 6.7 / DW1 — wiring them explicitly here means a future
    # rename of a preset key surfaces as a KeyError at process start,
    # not as a silent drop.
    assert 'initial_patience=patience_config["initial_patience"]' in source
    assert 'fail_penalty=patience_config["fail_penalty"]' in source
    assert 'silence_penalty=patience_config["silence_penalty"]' in source
    assert 'recovery_bonus=patience_config["recovery_bonus"]' in source
    assert 'silence_prompt_seconds=patience_config["silence_prompt_seconds"]' in source
    # Story 6.13 AC3 — per-difficulty stage-1 anchor threaded from the
    # resolved config. A forgotten thread would silently fall back to a
    # constructor default (no default exists today — would TypeError),
    # but a future default could mask a misconfigured YAML.
    assert (
        'ladder_impatience_seconds=patience_config["ladder_impatience_seconds"]'
        in source
    )
    assert 'silence_hangup_seconds=patience_config["silence_hangup_seconds"]' in source
    assert 'escalation_thresholds=patience_config["escalation_thresholds"]' in source
    assert 'total_checkpoints=patience_config["total_checkpoints"]' in source
    # Story 6.6 — new exit-line kwargs threaded into PatienceTracker.
    assert 'hang_up_line_silence=patience_config["hang_up_line_silence"]' in source
    assert (
        'hang_up_line_inappropriate=patience_config["hang_up_line_inappropriate"]'
        in source
    )
    assert 'hang_up_line_survived=patience_config["hang_up_line_survived"]' in source
    assert 'patience_warning_line=patience_config["patience_warning_line"]' in source
    # Story 6.6 — CheckpointManager + ExchangeClassifier instantiation.
    assert "ExchangeClassifier(" in source
    assert "CheckpointManager(" in source
    # 2026-05-29 — the main character LLM is built by the provider factory
    # (the single switch point); bot.py no longer constructs the service
    # inline.
    assert (
        "build_main_llm(settings, system_instruction=initial_system_prompt)" in source
    )
    # Story 6.9b — model id sourced from Settings so the operator can
    # flip providers via env override at deploy time without a code
    # release. The kwarg MUST land on the ExchangeClassifier
    # construction site (not just be referenced elsewhere) — a
    # forgotten thread would silently keep the hardcoded default.
    assert "model=settings.classifier_model" in source
    # 2026-05-29 provider abstraction — all LLM calls resolve key + base_url
    # via the `pipeline.llm_provider` helpers (the single switch point), not
    # a raw `settings.groq_api_key` / hardcoded URL. Asserted once via
    # `in source` (covers the classifier + emotion + warm-up call sites).
    assert "api_key=resolve_llm_api_key(settings)" in source
    # The raw-httpx LLM calls (classifier/emotion/warm-up) get the FULL
    # chat-completions endpoint, NOT the base — otherwise they 404.
    assert "base_url=resolve_llm_chat_url(settings)" in source
    assert "VisemeEmitter" not in source


def test_bot_pipeline_ordering() -> None:
    """`environment_monitor`, `checkpoint_manager`, and `patience_tracker`
    all sit BEFORE `context_aggregator.user()` so they observe raw finalized
    `TranscriptionFrame`s from STT before the aggregator consumes them
    (pipecat 0.0.108 `LLMUserAggregator._handle_transcription` does not
    push downstream — verified in source line 509-510). Story 6.6
    Deviations #5 (CheckpointManager) and #29 (PatienceTracker — added
    2026-05-18 post-deploy after the silence-ladder regression). The
    TTS → transport.output() ordering is asserted on its own (no longer
    split by a viseme_emitter step).

    Story 6.29 — `reply_sanitizer` is pinned on the REPLY side: AFTER
    `llm_first_text_probe` (probes measure raw LLM TTFT) and BEFORE
    `transcript_character` (transcript + TTS + the downstream assistant
    aggregator must all see CLEAN spoken text). A sanitizer drifting below
    `transcript_character` would record stage directions in the debrief
    transcript; below `tts` it would be inert for the voice — both break
    here loudly. (The retired `emotion_emitter` slot is asserted GONE.)

    Validated by scanning the Pipeline([...]) literal as a positional list.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    start = source.find("pipeline = Pipeline(")
    assert start != -1, "Pipeline construction site not found in bot.py"
    end = source.find("task = PipelineTask", start)
    assert end != -1, "Cannot find pipeline-block terminator"
    block = source[start:end]
    # Strip comment lines before scanning so a comment that happens to
    # mention a pipeline-element name (e.g. "the llm service") doesn't
    # poison the positional `find` lookup.
    block = "\n".join(
        line for line in block.splitlines() if not line.lstrip().startswith("#")
    )

    def _idx(needle: str) -> int:
        i = block.find(needle)
        assert i != -1, f"missing pipeline element: {needle!r}"
        return i

    # Story 6.6 Deviation #5 — checkpoint_manager BEFORE the aggregator
    # (pipecat consumes TranscriptionFrames internally).
    # Story 6.6 Deviation #29 — patience_tracker also BEFORE the
    # aggregator, same root cause. Its `_cancel_silence_timer()` path
    # on TranscriptionFrame observation was dormant in prod since
    # Story 6.4 (aggregator absorbed the frame). The bug surfaced on
    # the first Story 6.6 call: silence ladder ran through all stages
    # while user was actively speaking, hangup fired even after
    # checkpoint advanced.
    assert (
        # Story 6.9 review patch (D3) — endpoint_watchdog sits
        # immediately downstream of stt and BEFORE transcript_user so it
        # observes Soniox's raw TF stream first. The synthesised
        # finalized frame must propagate through transcript_user +
        # environment_monitor + checkpoint_manager + patience_tracker.
        _idx("endpoint_watchdog")
        < _idx("transcript_user")
        # Story 6.11 — EnvironmentMonitor observes raw finalized TFs
        # BEFORE the aggregator, same rationale.
        < _idx("environment_monitor")
        < _idx("checkpoint_manager")
        < _idx("patience_tracker")
        # Story 7.1 (AC11) — hesitation_observer sits adjacent to
        # patience_tracker (upstream of the output transport) so it sees both
        # BotStoppedSpeakingFrame (UPSTREAM) and UserStartedSpeakingFrame
        # (DOWNSTREAM). Moving it below transport.output() would silently kill
        # hesitation capture (it would never see BSF) — this pins the slot.
        < _idx("hesitation_observer")
        < _idx("context_aggregator.user()")
        < _idx("llm")
    )
    # Story 6.29 — the retired emotion_emitter must be GONE from the list.
    assert "emotion_emitter" not in block
    # Story 6.29 (AC2) — the sanitizer slot: probe → sanitizer →
    # transcript_character → tts → transport.output().
    assert (
        _idx("llm_first_text_probe")
        < _idx("reply_sanitizer")
        < _idx("transcript_character")
        < _idx("tts")
        < _idx("transport.output()")
    )


def test_bot_no_longer_reads_scenario_character_env_var() -> None:
    """Story 6.29 — the `SCENARIO_CHARACTER` env read fed ONLY the retired
    EmotionEmitter's classifier prompt; the read must be gone from bot.py
    (routes_calls still sets the env var — harmless, nothing consumes it)."""
    source = _BOT_PATH.read_text(encoding="utf-8")
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert 'os.environ.get("SCENARIO_CHARACTER")' not in code


def test_bot_reads_scenario_id_env_var() -> None:
    """Story 6.4 — `SCENARIO_ID` is the third env var injected by
    `routes_calls.initiate_call`. `bot.py` reads it with a fallback to
    the tutorial scenario for the legacy `/connect` path.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    assert 'os.environ.get("SCENARIO_ID")' in source
    assert "TUTORIAL_SCENARIO_ID" in source
    # Story 6.19 (kwarg re-anchored by 6.28) — bot.py threads the learner's
    # GLOBAL difficulty into the resolver:
    # `resolve_patience_config(scenario_id, difficulty=...)`. Absent → the
    # loaders fall back to scenarios.DEFAULT_DIFFICULTY (the authored
    # per-scenario fallback is gone). Assert the call + the threading, not the
    # old exact single-arg shape.
    assert "resolve_patience_config(" in source
    assert "difficulty=scenario_difficulty" in source


def test_on_first_participant_joined_queues_initial_envelope_via_task() -> None:
    """Story 6.7 AC1 + Phase 2 retouche #4 — `bot.py::
    on_first_participant_joined` MUST queue the initial
    `checkpoint_advanced(index=0)` envelope via
    `task.queue_frames([...])` (alongside the canned greeting
    `TTSSpeakFrame`), NOT via `checkpoint_manager.emit_initial_state()`.

    Why: `emit_initial_state` calls `push_frame` from the
    `CheckpointManager` processor, which pipecat's `_check_started`
    silently rejects when `StartFrame` hasn't yet propagated to that
    processor (`on_first_participant_joined` can fire BEFORE the
    StartFrame reaches `CheckpointManager`). The reject is logged as
    an ERROR but the frame is dropped — the client never sees the
    initial state envelope and the CheckpointStepper stays blank
    until the first real advance.

    `task.queue_frames` puts both frames into the task's source
    queue, which is drained AFTER StartFrame propagation. Both then
    flow downstream in order, reach `transport.output()`, and ship.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    # Strip comment-only lines so a `# was using emit_initial_state()`
    # docstring reference doesn't false-positive the regression-guard
    # assertion below (mirrors `test_bot_pipeline_ordering`).
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert '@transport.event_handler("on_first_participant_joined")' in code
    # Story 6.7 Phase 2 retouche #5 — the initial envelope is
    # scheduled by the manager (`schedule_initial_emit`); the
    # actual `push_frame` runs from inside `process_frame` on the
    # first post-StartFrame tick, so the envelope rides the same
    # downstream chain as the working `_classify_and_advance`
    # envelopes (no source-side `task.queue_frames` injection).
    assert "checkpoint_manager.schedule_initial_emit()" in code
    # Make sure we did NOT regress to the broken
    # `await checkpoint_manager.emit_initial_state()` pattern.
    assert "checkpoint_manager.emit_initial_state()" not in code


def test_bot_routes_playback_idle_to_patience_tracker() -> None:
    """Story 6.4 — the `on_data_received` event handler must route
    `{"type":"playback_idle"}` envelopes from the client onto
    `PatienceTracker.handle_playback_idle()`. This is the canonical
    silence-clock start signal, replacing the server-side
    `BotStoppedSpeakingFrame` trigger that suffered from a ~1 s
    frame-of-reference shift due to WebRTC jitter buffering.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    assert '@transport.event_handler("on_data_received")' in source
    assert 'envelope_type == "playback_idle"' in source
    assert "patience_tracker.handle_playback_idle()" in source


# ============================================================
# Story 6.8 Phase 2 — COHERENCE_CHARTER wiring (AC8 second assertion)
# ============================================================


def test_coherence_charter_threaded_to_checkpoint_manager_and_llm_settings() -> None:
    """Story 6.8 Phase 2 AC8 — source-text wiring assertions for the
    charter. The charter MUST be:
      - imported from `pipeline.prompts` (else `bot.py` would crash at
        import after the constant is added);
      - threaded into the `CheckpointManager(...)` constructor as the
        `coherence_charter=COHERENCE_CHARTER` kwarg (else the manager
        would refuse construction because the kwarg is required);
      - composed into the initial `system_instruction` passed to the main
        LLM (via `build_main_llm(settings, system_instruction=...)`) so the
        FIRST LLM turn already has coherence rules (without this, the very
        first user turn would be answered under a charter-less prompt and
        the smoke gate's call_id=118 replay would fail).

    Source-text matching is fragile (renames break it) — when bot.py
    refactors, expect to re-verify the assertions.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")

    # Import wiring.
    assert "COHERENCE_CHARTER" in source, (
        "bot.py must import COHERENCE_CHARTER from pipeline.prompts so "
        "the symbol is in scope for the CheckpointManager kwarg + the "
        "initial system_instruction composition"
    )

    # Manager kwarg wiring — strip comment-only lines so a docstring
    # mention of the kwarg doesn't false-positive.
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert "coherence_charter=COHERENCE_CHARTER" in code, (
        "bot.py must thread coherence_charter=COHERENCE_CHARTER into "
        "the CheckpointManager(...) constructor — the kwarg is required, "
        "a missing thread would surface as TypeError at call init"
    )

    # Initial composition wiring — the charter must be slotted into the
    # initial `system_instruction` so the first user turn already gets
    # coherence. Story 6.13: anchor on the composition block + the LLM's
    # consumption of it, NOT on raw proximity (the old `llm_start - 800`
    # window broke when the DTLN env-gate was added between the
    # composition and the LLM construction — exactly the "fragile on
    # refactor" caveat above).
    assert "system_instruction=initial_system_prompt" in code, (
        "the main LLM must be built with system_instruction="
        "initial_system_prompt so the first LLM turn uses the composed "
        "prompt (base + charter + remaining-goals blocks)"
    )
    comp_start = code.find("initial_system_prompt = (")
    assert comp_start != -1, (
        "expected the `initial_system_prompt = (...)` composition block in bot.py"
    )
    composition_block = code[comp_start : comp_start + 600]
    assert "COHERENCE_CHARTER" in composition_block, (
        "the initial_system_prompt composition must slot COHERENCE_CHARTER "
        "between base_prompt and the first checkpoint's prompt_segment so "
        "the first user turn already gets coherence rules — without this, "
        "call_id=118 replay would still see Tina forget the Coke 70 s later"
    )


# ============================================================
# Story 6.6 — Déviation-#28 pipeline-drive contract test
# (deferred-work line 369)
# ============================================================


def test_checkpoint_manager_observes_finalized_TranscriptionFrame_via_real_pipeline_drive():
    """**THIS IS THE DÉVIATION-#28 / #5 REGRESSION NET.**

    Background: Story 6.4 / 6.5 Déviation #28 was a silent 2-day prod
    regression because the unit test hard-coded `FrameDirection.DOWNSTREAM`
    when invoking `process_frame()` directly. Pipecat's real routing put
    `BotStoppedSpeakingFrame` UPSTREAM-only past `PatienceTracker`, so
    the production direction check (DOWNSTREAM) never fired.

    Story 6.6 Deviation #5: the FIRST deploy of CheckpointManager had it
    placed AFTER `context_aggregator.user()` (per the original spec).
    The `LLMUserAggregator` CONSUMES `TranscriptionFrame`s
    (see `llm_response_universal.py:509-510` — no `push_frame` after
    `_handle_transcription`), so the manager downstream of it never
    received a single TF. Zero classifier calls fired in prod on Test 1.
    The original version of this test used `Pipeline([manager])` alone
    (no aggregator), so it passed despite the bug — same trap as
    Déviation #28 (test setup that doesn't include the upstream
    processor that absorbs frames).

    This rewritten test now drives a TranscriptionFrame through a
    pipeline that **includes the real `LLMContextAggregatorPair.user()`**
    — i.e. the exact upstream processor the manager sits next to in
    `bot.py`. If a future refactor moves the manager to a position
    downstream of an absorber (any aggregator, gate, filter that
    consumes the frame type), this test breaks loud.

    See `server/CLAUDE.md` §1 "Frame-direction tests" for the broader
    pattern and project memory 🪤 `feedback_pipecat_frame_direction_test_trap.md`.
    """
    import asyncio
    from unittest.mock import MagicMock

    from pipecat.frames.frames import EndFrame, TranscriptionFrame
    from pipecat.pipeline.pipeline import Pipeline
    from pipecat.pipeline.runner import PipelineRunner
    from pipecat.pipeline.task import PipelineTask
    from pipecat.processors.aggregators.llm_context import LLMContext
    from pipecat.processors.aggregators.llm_response_universal import (
        LLMContextAggregatorPair,
    )

    from pipeline.checkpoint_manager import CheckpointManager
    from pipeline.exchange_classifier import ExchangeClassifier

    # Stub LLM that exposes the `._settings.system_instruction` field
    # CheckpointManager mutates on advance.
    class _StubSettings:
        def __init__(self) -> None:
            self.system_instruction = "initial"

    class _StubLLM:
        def __init__(self) -> None:
            self._settings = _StubSettings()

    # Track classifier invocations.
    invoked_with: list[dict] = []

    classifier = ExchangeClassifier(api_key="test-key")

    # Story 6.10 — the manager now calls `classify_multi` (goal-based
    # dialogue). Stub it so the real Groq HTTP path is never hit; return
    # all-unmet so no goal flips — we only need to prove the multi-goal
    # classify path RAN end-to-end through a real pipeline.
    async def _stub_classify_multi(**kwargs):
        invoked_with.append(kwargs)
        return {g["id"]: False for g in kwargs["pending_goals"]}

    classifier.classify_multi = _stub_classify_multi  # type: ignore[assignment]

    checkpoints = [
        dict(
            id="cp0",
            hint_text="hint",
            prompt_segment="segment",
            success_criteria="User said something.",
        )
    ]

    patience_tracker = MagicMock()
    # Story 6.22 — process_frame now early-suppresses finalized user turns when
    # `is_hanging_up` is truthy; a bare auto-Mock would drop this contract
    # test's TF before the classifier runs (and the `is_terminal_turn`
    # comparison needs real ints). Pin a real non-hang-up tracker.
    patience_tracker.is_hanging_up = False
    patience_tracker.patience = 100
    patience_tracker.fail_penalty = -15

    manager = CheckpointManager(
        base_prompt="BASE.",
        checkpoints=checkpoints,
        llm=_StubLLM(),
        llm_context=LLMContext(),
        classifier=classifier,
        patience_tracker=patience_tracker,
        scenario_description="contract-test",
        coherence_charter="CHARTER.",
    )

    # Build a pipeline that mirrors `bot.py`'s production ordering for
    # the user-side processors: manager sits BEFORE the user aggregator
    # (Deviation #5). The aggregator consumes TranscriptionFrames
    # internally; if the manager were placed AFTER it (as the original
    # spec said), this test would fail with zero classifier calls — the
    # exact prod regression we're guarding against. We use the default
    # `LLMContextAggregatorPair` constructor (no VAD, no turn strategies)
    # because the test only needs to prove the aggregator absorbs the
    # frame — full turn-boundary detection is irrelevant here AND the
    # SileroVADAnalyzer transitively imports torch which contaminates
    # the test environment for later tests.
    context = LLMContext()
    aggregator_pair = LLMContextAggregatorPair(context)
    pipeline = Pipeline([manager, aggregator_pair.user()])
    task = PipelineTask(pipeline)

    async def _drive() -> None:
        await task.queue_frames(
            [
                TranscriptionFrame(
                    text="I want chicken.",
                    user_id="user",
                    timestamp="2026-05-15T12:00:00Z",
                    finalized=True,
                ),
                EndFrame(),
            ]
        )
        runner = PipelineRunner()
        await runner.run(task)
        # The classifier task may still be in flight after the pipeline
        # tears down — drain it explicitly.
        if manager._in_flight is not None:
            await asyncio.gather(manager._in_flight, return_exceptions=True)

    asyncio.run(_drive())

    assert invoked_with, (
        "DÉVIATION-#28 REGRESSION: CheckpointManager did NOT observe the "
        "TranscriptionFrame when driven through a real PipelineTask. "
        "Either pipecat changed its frame-routing direction for "
        "TranscriptionFrame (re-verify against `pipecat.frames.frames` "
        "and `pipeline/bot.py` ordering) or the processor was moved to "
        "a position where user transcriptions don't reach it. The "
        "ExchangeClassifier will be inert in prod and no goal "
        "will ever flip — same failure mode as the Story 6.4 "
        "silence-ladder regression."
    )
    assert invoked_with[0]["user_text"] == "I want chicken."
    # Story 6.10 — the multi-goal classify path received the pending
    # goals (one entry per checkpoint on the first turn).
    pending = invoked_with[0]["pending_goals"]
    assert [g["id"] for g in pending] == ["cp0"]


# ============================================================
# Story 6.22 — post-hang-up suppression survives real pipeline routing
# ============================================================


def test_post_hangup_user_turn_suppressed_via_real_pipeline_drive():
    """Story 6.22 AC5 (pipeline-drive variant, server/CLAUDE.md §1) — drive a
    finalized user TranscriptionFrame through a REAL PipelineTask while the
    PatienceTracker is ALREADY hanging up. The CheckpointManager must DROP it:
    a recorder placed immediately downstream never sees it (so it never reaches
    `context_aggregator.user()` / the LLM, which would generate a reply over the
    exit line), and the classifier is never invoked. Proves the no-overlap
    guarantee holds under real pipecat routing, not just a mocked process_frame
    call — the mirror of the Déviation-#28 observe-the-frame contract test
    above (that one asserts the frame IS seen on a normal call; this one that
    it is NOT seen during a hang-up)."""
    import asyncio
    from unittest.mock import MagicMock

    from pipecat.frames.frames import EndFrame, TranscriptionFrame
    from pipecat.pipeline.pipeline import Pipeline
    from pipecat.pipeline.runner import PipelineRunner
    from pipecat.pipeline.task import PipelineTask
    from pipecat.processors.aggregators.llm_context import LLMContext
    from pipecat.processors.aggregators.llm_response_universal import (
        LLMContextAggregatorPair,
    )
    from pipecat.processors.frame_processor import FrameDirection, FrameProcessor

    from pipeline.checkpoint_manager import CheckpointManager
    from pipeline.exchange_classifier import ExchangeClassifier

    class _StubSettings:
        def __init__(self) -> None:
            self.system_instruction = "initial"

    class _StubLLM:
        def __init__(self) -> None:
            self._settings = _StubSettings()

    class _Recorder(FrameProcessor):
        """Records TranscriptionFrames that make it PAST the manager."""

        def __init__(self) -> None:
            super().__init__()
            self.seen: list[str] = []

        async def process_frame(self, frame: object, direction: FrameDirection) -> None:
            await super().process_frame(frame, direction)
            if isinstance(frame, TranscriptionFrame):
                self.seen.append(frame.text)
            await self.push_frame(frame, direction)

    invoked_with: list[dict] = []
    classifier = ExchangeClassifier(api_key="test-key")

    async def _stub_classify_multi(**kwargs):
        invoked_with.append(kwargs)
        return {g["id"]: False for g in kwargs["pending_goals"]}

    classifier.classify_multi = _stub_classify_multi  # type: ignore[assignment]

    checkpoints = [
        dict(
            id="cp0",
            hint_text="hint",
            prompt_segment="segment",
            success_criteria="User said something.",
        )
    ]

    # Tracker already hanging up — the state AFTER the triggering terminal turn
    # scheduled the exit line.
    patience_tracker = MagicMock()
    patience_tracker.is_hanging_up = True
    patience_tracker.patience = 0
    patience_tracker.fail_penalty = -15

    manager = CheckpointManager(
        base_prompt="BASE.",
        checkpoints=checkpoints,
        llm=_StubLLM(),
        llm_context=LLMContext(),
        classifier=classifier,
        patience_tracker=patience_tracker,
        scenario_description="post-hangup-contract-test",
        coherence_charter="CHARTER.",
    )

    recorder = _Recorder()
    context = LLMContext()
    aggregator_pair = LLMContextAggregatorPair(context)
    pipeline = Pipeline([manager, recorder, aggregator_pair.user()])
    task = PipelineTask(pipeline)

    async def _drive() -> None:
        await task.queue_frames(
            [
                TranscriptionFrame(
                    text="Maybe you are someone else.",
                    user_id="user",
                    timestamp="2026-06-04T12:00:00Z",
                    finalized=True,
                ),
                EndFrame(),
            ]
        )
        runner = PipelineRunner()
        await runner.run(task)
        if manager._in_flight is not None:
            await asyncio.gather(manager._in_flight, return_exceptions=True)

    asyncio.run(_drive())

    assert invoked_with == [], (
        "post-hang-up turn must NOT be classified — a generated/normal reply "
        "would play over the exit line (Story 6.22 AC1/AC2)"
    )
    assert recorder.seen == [], (
        "post-hang-up turn must NOT be forwarded downstream past the "
        "CheckpointManager — it would reach the LLM and overlap the exit line"
    )


# ============================================================
# Story 6.18 — dynamic exit/patience-warning line generator wiring
# ============================================================


def test_bot_wires_dynamic_exit_line_generator_into_patience_tracker() -> None:
    """Story 6.18 — `bot.py` must:
      - import `generate_exit_line` from `pipeline.exit_line_generator`;
      - gate the feature on `settings.hangup_line_generation` (AC7 kill-switch);
      - build a closure that calls `generate_exit_line(...)` reading the LIVE
        transcript (`context.get_messages()`) + the bare persona + charter;
      - thread the resulting callable into PatienceTracker via
        `hang_up_line_generator=...`.

    Source-text matching is fragile (renames break it) — when bot.py refactors,
    re-verify these assertions.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    assert "from pipeline.exit_line_generator import generate_exit_line" in source

    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    # AC7 kill-switch — the whole feature is gated on the Settings flag.
    assert "settings.hangup_line_generation" in code, (
        "bot.py must gate dynamic exit-line generation on "
        "settings.hangup_line_generation (HANGUP_LINE_GENERATION env toggle)"
    )
    # The closure must actually call the generator with the live transcript.
    assert "generate_exit_line(" in code
    assert "context.get_messages()" in code, (
        "the generator closure must read the LIVE transcript at hang-up time "
        "so the line reflects what actually happened"
    )
    # Story 6.18 review (Decision #2 / Option A) — the closure must accept and
    # append the suppressed winning user turn on the survived path.
    assert "extra_user_text" in code, (
        "bot.py closure must accept extra_user_text and append the winning "
        "user turn to the transcript for the survived path"
    )
    # The callable is threaded into PatienceTracker (a missing thread would
    # silently leave the canned-line-only behaviour).
    assert "hang_up_line_generator=hang_up_line_generator" in code, (
        "bot.py must thread the generator into PatienceTracker via "
        "hang_up_line_generator=..."
    )


def test_bot_teardown_merges_device_and_server_hesitations() -> None:
    """Story 7.6 (AC6) — the teardown must feed `persist_debrief` the MERGED
    hesitations (device-authoritative), NOT the bare server observer. This is
    the source-text wiring guard for the 7.5 "merge never called" finding: a
    revert to `hesitations=hesitation_observer.top_hesitations()` (the dormant
    pre-7.6 wiring) fails here loudly.

    Pairs with `test_persist_stores_device_sourced_hesitation_from_merge`
    (test_debrief_teardown.py), which proves the merged device gap actually
    reaches the persisted row. Source-text matching is fragile (renames break
    it) — re-verify on a bot.py refactor.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    assert "merge_hesitation_sources" in source, (
        "bot.py must import merge_hesitation_sources from "
        "pipeline.device_hesitation_collector"
    )
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    # The merge result — not the bare observer — is what feeds persist_debrief.
    assert "hesitations=merge_hesitation_sources(" in code, (
        "bot.py teardown must pass hesitations=merge_hesitation_sources(...) to "
        "persist_debrief — a bare hesitation_observer.top_hesitations() is the "
        "dormant pre-7.6 wiring (device source never used)"
    )
    assert "device_hesitation_collector.top_hesitations()" in code, (
        "the merge must take the device collector's gaps as the authoritative "
        "(first) source"
    )
    assert "hesitation_observer.top_hesitations()" in code, (
        "the merge must take the server observer's gaps as the fallback "
        "(second) source — its UNRESOLVED re-speak freezes are still added"
    )


def test_bot_sources_user_speech_timeout_from_settings() -> None:
    """Story 6.18 smoke gate (call_id=215) — the turn-endpoint timeout must be
    sourced from Settings (USER_SPEECH_TIMEOUT), not hardcoded, so it's tunable
    on the VPS without a redeploy. 0.6 s chopped B1 hesitations ("Do you, uh,
    ooh.") into separate turns judged as failures (unfair patience drain)."""
    source = _BOT_PATH.read_text(encoding="utf-8")
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert "user_speech_timeout=settings.user_speech_timeout" in code, (
        "bot.py must source user_speech_timeout from Settings, not hardcode it"
    )
    assert "user_speech_timeout=0.6" not in code, (
        "must not regress to the hardcoded 0.6 s that chopped B1 thinking pauses"
    )


def test_bot_fires_classifier_warmup_at_call_start() -> None:
    """Story 6.27 (D2a / AC4) — bot.py must fire `exchange_classifier.warm_up()`
    fire-and-forget right after construction, with the 6.24/6.26 strong-ref +
    done-callback pattern (a bare create_task can be GC'd mid-flight). The
    llm_warmup does NOT cover this: it warms Groq through its own throwaway
    client, while the classifier's lazy client paid a cold TLS handshake on
    the FIRST classify — which blew the 1.5 s budget and silently lost the
    opening turn on calls 265/266."""
    source = _BOT_PATH.read_text(encoding="utf-8")
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert "asyncio.create_task(exchange_classifier.warm_up())" in code, (
        "bot.py must fire the classifier warm-up at call start (D2a)"
    )
    assert "_BACKGROUND_TASKS.add(_classifier_warmup_task)" in code, (
        "the warm-up task needs the strong-ref pattern (6.26 review lesson)"
    )
    assert (
        "_classifier_warmup_task.add_done_callback(_BACKGROUND_TASKS.discard)" in code
    )


# ============================================================
# Story 6.29 — reply sanitizer + mood directive + verdict-wait wiring
# ============================================================


def test_bot_wires_reply_sanitizer_mood_directive_and_wait_budget() -> None:
    """Story 6.29 — source-text wiring contract (mirrors the 6.27 warm-up
    wiring test). bot.py must:
      - import MOOD_TAG_DIRECTIVE and append it to the initial
        `initial_system_prompt` composition (AC8 — the FIRST reply already
        co-generates its mood tag; CheckpointManager's composer appends it
        by default on every recompose);
      - keep the directive OUT of `exit_line_persona` (exit/warning lines
        ride TTSSpeakFrames that bypass the sanitizer — a tag there would
        be SPOKEN);
      - thread `verdict_wait_budget_ms=settings.verdict_wait_budget_ms`
        into CheckpointManager (D1 bounded wait, env VERDICT_WAIT_BUDGET_MS).

    Source-text matching is fragile (renames break it) — when bot.py
    refactors, re-verify these assertions.
    """
    source = _BOT_PATH.read_text(encoding="utf-8")
    code = "\n".join(
        line for line in source.splitlines() if not line.lstrip().startswith("#")
    )
    assert "MOOD_TAG_DIRECTIVE" in code, (
        "bot.py must import MOOD_TAG_DIRECTIVE from pipeline.prompts"
    )
    comp_start = code.find("initial_system_prompt = (")
    assert comp_start != -1
    composition_block = code[comp_start : code.find("exit_line_persona", comp_start)]
    assert "MOOD_TAG_DIRECTIVE" in composition_block, (
        "the initial_system_prompt composition must append MOOD_TAG_DIRECTIVE "
        "(AC8 — boot parity with CheckpointManager's recompose)"
    )
    assert "exit_line_persona = scenario_base_prompt.rstrip()" in code, (
        "exit_line_persona must stay the BARE persona — no mood directive "
        "(exit lines bypass the sanitizer; a tag would be spoken)"
    )
    assert "verdict_wait_budget_ms=settings.verdict_wait_budget_ms" in code, (
        "bot.py must thread the D1 bounded-wait budget from Settings into "
        "CheckpointManager — a forgotten thread silently pins the constructor "
        "default and disconnects the VERDICT_WAIT_BUDGET_MS env knob"
    )


def test_reply_sanitizer_cleans_stream_and_emits_mood_via_real_pipeline_drive():
    """Story 6.29 AC2 + AC8 (pipeline-drive variant, server/CLAUDE.md §1) —
    drive a realistic streamed LLM reply through a REAL PipelineTask
    containing the ReplySanitizer (so `setup()` runs — the `_clock`-trap
    class of bug surfaces loud) and assert at the downstream boundary:

      - parenthetical + asterisk spans are stripped, split across frames;
      - the trailing mood tag (split mid-tag across two frames) never
        reaches downstream text;
      - exactly one `emotion` envelope with the EmotionEmitter-compatible
        shape is emitted at end of reply;
      - a TTSSpeakFrame (PatienceTracker-owned exit line) passes untouched.
    """
    import asyncio

    from pipecat.frames.frames import (
        EndFrame,
        LLMFullResponseEndFrame,
        LLMFullResponseStartFrame,
        LLMTextFrame,
        OutputTransportMessageFrame,
        TextFrame,
        TTSSpeakFrame,
    )
    from pipecat.pipeline.pipeline import Pipeline
    from pipecat.pipeline.runner import PipelineRunner
    from pipecat.pipeline.task import PipelineTask
    from pipecat.processors.frame_processor import FrameProcessor

    from pipeline.reply_sanitizer import ReplySanitizer

    class _Recorder(FrameProcessor):
        def __init__(self) -> None:
            super().__init__()
            self.texts: list[str] = []
            self.envelopes: list[dict] = []
            self.tts_speak: list[str] = []

        async def process_frame(self, frame, direction) -> None:
            await super().process_frame(frame, direction)
            if isinstance(frame, TTSSpeakFrame):
                self.tts_speak.append(frame.text)
            elif isinstance(frame, TextFrame):
                self.texts.append(frame.text)
            elif isinstance(frame, OutputTransportMessageFrame):
                self.envelopes.append(frame.message)
            await self.push_frame(frame, direction)

    sanitizer = ReplySanitizer()
    recorder = _Recorder()
    pipeline = Pipeline([sanitizer, recorder])
    task = PipelineTask(pipeline)

    async def _drive() -> None:
        await task.queue_frames(
            [
                LLMFullResponseStartFrame(),
                LLMTextFrame(text="Fine, grilled chicken "),
                LLMTextFrame(text="(noting the"),
                LLMTextFrame(text=" order) *scribbles* it is."),
                LLMTextFrame(text=" <mo"),
                LLMTextFrame(text="od:smirk>"),
                LLMFullResponseEndFrame(),
                TTSSpeakFrame(text="*heavy sigh* I'm done."),
                EndFrame(),
            ]
        )
        runner = PipelineRunner()
        await runner.run(task)

    asyncio.run(_drive())

    spoken = "".join(recorder.texts)
    assert "(" not in spoken and ")" not in spoken, spoken
    assert "*" not in spoken, spoken
    assert "<mood" not in spoken and "smirk>" not in spoken, spoken
    assert "Fine, grilled chicken" in spoken
    assert "it is." in spoken
    emotion = [e for e in recorder.envelopes if e.get("type") == "emotion"]
    assert len(emotion) == 1, recorder.envelopes
    assert emotion[0]["data"]["emotion"] == "smirk"
    assert isinstance(emotion[0]["data"]["intensity"], float)
    assert recorder.tts_speak == ["*heavy sigh* I'm done."]


def test_late_transcription_after_bounded_wait_yields_single_llm_run():
    """Story 6.29 AC7 (THE load-bearing drive test, server/CLAUDE.md §1) —
    the D1 bounded wait holds the finalized user TranscriptionFrame inside
    CheckpointManager while the verdict lands. This drives the REAL
    `LLMContextAggregatorPair.user()` with bot.py's REAL turn strategies
    (MinWords start + SpeechTimeout stop) and proves the architecture claim:
    the turn-end trigger WAITS for the finalized transcript (pipecat's
    SpeechTimeoutUserTurnStopStrategy gates on `_transcript_finalized` and
    its empty-text early-return), so a TF delayed PAST `user_speech_timeout`
    still yields exactly ONE LLM run containing the FULL user text — no
    empty-context run when the VAD-stop timer fires mid-hold, no dropped
    turn.
    """
    import asyncio
    import time as _time
    from unittest.mock import MagicMock

    from pipecat.frames.frames import (
        EndFrame,
        InterimTranscriptionFrame,
        LLMContextFrame,
        TranscriptionFrame,
        VADUserStartedSpeakingFrame,
        VADUserStoppedSpeakingFrame,
    )
    from pipecat.pipeline.pipeline import Pipeline
    from pipecat.pipeline.runner import PipelineRunner
    from pipecat.pipeline.task import PipelineTask
    from pipecat.processors.aggregators.llm_context import LLMContext
    from pipecat.processors.aggregators.llm_response_universal import (
        LLMContextAggregatorPair,
        LLMUserAggregatorParams,
    )
    from pipecat.processors.frame_processor import FrameProcessor
    from pipecat.turns.user_start import MinWordsUserTurnStartStrategy
    from pipecat.turns.user_stop import SpeechTimeoutUserTurnStopStrategy
    from pipecat.turns.user_turn_strategies import UserTurnStrategies

    from pipeline.checkpoint_manager import CheckpointManager
    from pipeline.exchange_classifier import ExchangeClassifier

    class _StubSettings:
        def __init__(self) -> None:
            self.system_instruction = "initial"

    class _StubLLM:
        def __init__(self) -> None:
            self._settings = _StubSettings()

    class _RunRecorder(FrameProcessor):
        """Captures every LLMContextFrame = one LLM run."""

        def __init__(self) -> None:
            super().__init__()
            self.runs: list = []

        async def process_frame(self, frame, direction) -> None:
            await super().process_frame(frame, direction)
            if isinstance(frame, LLMContextFrame):
                self.runs.append(frame)
            await self.push_frame(frame, direction)

    user_text = "I want the grilled chicken please."
    classify_calls: list[dict] = []

    classifier = ExchangeClassifier(api_key="test-key")

    async def _slow_classify_multi(**kwargs):
        classify_calls.append(kwargs)
        # Verdict lands 0.35 s in — well past user_speech_timeout (0.1 s)
        # but inside the 800 ms wait budget, so the manager holds the TF
        # for the verdict BEFORE forwarding (AC7).
        await asyncio.sleep(0.35)
        return {g["id"]: False for g in kwargs["pending_goals"]}

    classifier.classify_multi = _slow_classify_multi  # type: ignore[assignment]

    checkpoints = [
        dict(
            id="cp0",
            hint_text="hint",
            prompt_segment="segment",
            success_criteria="User ordered a dish.",
        ),
        dict(
            id="cp1",
            hint_text="hint2",
            prompt_segment="segment2",
            success_criteria="User picked a drink.",
        ),
    ]

    patience_tracker = MagicMock()
    patience_tracker.is_hanging_up = False
    patience_tracker.patience = 100
    patience_tracker.fail_penalty = -15

    manager = CheckpointManager(
        base_prompt="BASE.",
        checkpoints=checkpoints,
        llm=_StubLLM(),
        llm_context=LLMContext(),
        classifier=classifier,
        patience_tracker=patience_tracker,
        scenario_description="ac7-drive-test",
        coherence_charter="CHARTER.",
        verdict_wait_budget_ms=800,
    )

    context = LLMContext()
    aggregator_pair = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            user_turn_strategies=UserTurnStrategies(
                start=[
                    MinWordsUserTurnStartStrategy(
                        min_words=3, enable_interruptions=True
                    )
                ],
                # user_speech_timeout DELIBERATELY far below the 0.35 s
                # verdict hold — the exact "wait exceeds user_speech_timeout"
                # case AC7 names.
                stop=[SpeechTimeoutUserTurnStopStrategy(user_speech_timeout=0.1)],
            ),
        ),
    )
    recorder = _RunRecorder()
    pipeline = Pipeline([manager, aggregator_pair.user(), recorder])
    task = PipelineTask(pipeline)

    async def _drive() -> None:
        runner = PipelineRunner()
        run_task = asyncio.create_task(runner.run(task))

        # Realistic pacing matters: the user-turn START broadcasts an
        # interruption (pipecat cancels each processor's in-process frame).
        # In prod that fires while the user BEGINS speaking — always before
        # STT can finalize the turn — so the finalized TF must be queued
        # AFTER the start-interruption has propagated, exactly like prod.
        await task.queue_frame(VADUserStartedSpeakingFrame())
        # Interim TF (>=3 words) starts the user turn via MinWords — passes
        # the manager unheld (finalized defaults False).
        await task.queue_frame(
            InterimTranscriptionFrame(
                text=user_text,
                user_id="user",
                timestamp="2026-06-10T12:00:00Z",
            )
        )
        await asyncio.sleep(0.15)  # let the turn-start interruption settle
        # VAD stop arms the strategy's stop timer NOW — it fires mid-hold
        # with NO finalized text (the empty-text early return = no
        # empty-context run).
        await task.queue_frame(
            VADUserStoppedSpeakingFrame(stop_secs=0.8, timestamp=_time.time())
        )
        await task.queue_frame(
            TranscriptionFrame(
                text=user_text,
                user_id="user",
                timestamp="2026-06-10T12:00:01Z",
                finalized=True,
            )
        )
        # Hold (0.35 s) + stop trigger + aggregation push, with margin.
        await asyncio.sleep(0.9)
        await task.queue_frame(EndFrame())
        await run_task
        if manager._in_flight is not None:
            await asyncio.gather(manager._in_flight, return_exceptions=True)

    asyncio.run(_drive())

    assert classify_calls, "the held turn must still be classified"
    assert len(recorder.runs) == 1, (
        f"expected exactly ONE LLM run for the delayed TF, got "
        f"{len(recorder.runs)} — an empty-context run or a dropped turn "
        f"breaks AC7"
    )
    messages = recorder.runs[0].context.get_messages()
    user_messages = [m for m in messages if m.get("role") == "user"]
    assert user_messages, f"no user message reached the LLM context: {messages}"
    assert user_text in str(user_messages[-1].get("content")), (
        "the LLM run must contain the FULL user text (no truncated/partial "
        "turn after the bounded wait)"
    )
